# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FontaineGuo Blog 
email: Fontaine(X)Guo@163.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Fontaine Guo, a game designer and programmar. I'm trying
  to be a tech artist and you're interested in game dev or painting,
  you could email me and have a communication in the field you like.
  
  p.s:
    my email address don't have  "(X)", just for keeping trash email
  senders out.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://FontaineGuo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Files
pagesdir: pages
assets:
  libs: assets/libs
  owner: assets/owner
logo: logo.png
search: true
share: true
comments: true

discus_shortname: MADness

# Social networking links used in footer. Update and remove as you like.
github_username:  FontaineGuo
instagram_username: FontaineGuo

# Owner/author information
owner:
  name:   Fontaine Guo
  avatar: avatar.jpg
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    MAD for Jekyll

#dependencies
# Gems
gems:
  - jekyll-feed
  - jekyll-paginate


# Build settings
highlighter:         rouge
markdown: kramdown
theme: minima

kramdown:
    extensions:     
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed
paginate: 5
paginate_path: "/writing/page:num/"
permalink: "/writing/:title/"
slugify: "pretty"
exclude:
  - Gemfile
  - Gemfile.lock